version: '3.3'

services:
  web:
    image: pusl2020-web
    build:
      context: ../
      args:
        TELERIK_USERNAME: ${TELERIK_USERNAME:-}
        TELERIK_PASSWORD: ${TELERIK_PASSWORD:-}
    ports:
      - 5000:80 
    depends_on:
      - mssql
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_PASSWORD:-yourStrong(!)Password}
    ports:
      - "1433:1433"
    volumes:
        - mssql_data:/var/opt/mssql

  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2022-04-16T04-26-02Z
    restart: unless-stopped
    expose:
      - "9000"
      - "9001"
    command: server /data
    volumes:
      - minio_data:/data

volumes:
  mssql_data:
  minio_data: