version: '3.3'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
  mssql:
    ports:
      - "1433:1433"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_CONSOLE_ADDRESS: ":9001"
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-}
      MINIO_SECRET_KEY:  ${MINIO_SECRET_KEY:-}
    command: server --console-address ":9001" /data

